### PR TITLE
fix: special characters in object literals

### LINKED ISSUE #13: Code blocks containing 'xxx' are not displayed correctly.
## ScreenShot
image

## Case
```typescript
const a = { 'a-a': '11' }

const b:a = '11'
```

### PR DESCRIPTION
**Pull request by costamatheus97**
Fixes #13 

Please let me know if there is any guidelines to follow for contribution @yoavbls

### CODE REVIEW

**Comment by yoavbls** [comment]
Thank you for opening to fixing this issue and also added a test 😍
I'll take a deep look later today to make sure it isn't causing some other random errors to break
thanks!

**Review by jenspo — APPROVED** [review]

**Review by edmolima — APPROVED** [review]

File: src/format/formatDiagnosticMessage.ts [hunk 1]
```diff
@@ -15,10 +15,19 @@ const formatTypeOrModuleBlock = (_: string, prefix: string, code: string) =>
...
   );
 
-export const formatDiagnosticMessage = (message: string) =>
-  message
+const formatObjectLiterals = (message: string) => {
+  const objectLiteralRegex = /'(\{.*?\})'/g;
+  return message.replace(objectLiteralRegex, (_: string, p1: string) => {
+    return unstyledCodeBlock(p1);
+  });
+};
```
Comment (yoavbls) [inline src/format/formatDiagnosticMessage.ts:23]: This regex is too comprehensive for returning an unstyled code block, I think we should handle this case like all the other replaces.

The original issue looks like one of these regexes matches on the wrong closing `'`.
probably it's this replace because it's the most common:
CleanShot 2023-04-19 at 02 37 49@2x
the `.` is optional so maybe we'll need to replace it by non optional `.` or whitespace

File: src/test/suite/extension.test.ts [hunk 2]
```diff
@@ -15,4 +16,11 @@ suite("Extension Test Suite", () => {
       "Hello, {world! [This] is a (test.)}"
     );
   });
+
+  test("Special characters in object keys", () => {
+    assert.strictEqual(
+      formatDiagnosticMessage("Type 'string' is not assignable to type '{ 'abc*bc': string; }'.").match(/<code>(.*?)<\/code>/)?.[0],
+      "<code>{ 'abc*bc': string; }</code>"
+    );
+  });
```
Comment (yoavbls) [inline src/test/suite/extension.test.ts:25]: We'll have to format these cases so they'll no longer be an unstyled code block so the test has to be changed too

**Review by yoavbls — CHANGES_REQUESTED** [review]
Thank you for your contribution!
I prefer that we'll solve these cases instead of returning unstyled code block
let me know if you need more information or help 🙂

**Comment by costamatheus97** [comment]
Done! indeed there was an issue with the regex you mentioned, could fix with the solution you've provided. Had to change the last regex also, had to use a negative lookahead to prevent it from adding a code block inside the type error. 

Let me know if there is any persisting issues

File: package.json [hunk 3]
```diff
@@ -54,7 +54,7 @@
   "scripts": {
     "vscode:prepublish": "npm run package",
     "compile": "node scripts/build",
-    "watch": "npm run compile -- --watch",
```
Comment (yoavbls) [inline package.json:57]: I think it's an intended change. Isn't it work for you? (because `npm run compile --watch` is not working for me)

**Review by yoavbls — APPROVED** [review]
Works great, thank you @costamatheus97 🙂
